// Generated by gencpp from file vision/bottle_data.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_BOTTLE_DATA_H
#define VISION_MESSAGE_BOTTLE_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace vision
{
template <class ContainerAllocator>
struct bottle_data_
{
  typedef bottle_data_<ContainerAllocator> Type;

  bottle_data_()
    : P()
    , height(0.0)
    , width(0.0)
    , type(0)  {
    }
  bottle_data_(const ContainerAllocator& _alloc)
    : P(_alloc)
    , height(0.0)
    , width(0.0)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _P_type;
  _P_type P;

   typedef double _height_type;
  _height_type height;

   typedef double _width_type;
  _width_type width;

   typedef int32_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::vision::bottle_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::bottle_data_<ContainerAllocator> const> ConstPtr;

}; // struct bottle_data_

typedef ::vision::bottle_data_<std::allocator<void> > bottle_data;

typedef boost::shared_ptr< ::vision::bottle_data > bottle_dataPtr;
typedef boost::shared_ptr< ::vision::bottle_data const> bottle_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::bottle_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::bottle_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vision': ['/home/ctai/catkin_ws2/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::bottle_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::bottle_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::bottle_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::bottle_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::bottle_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::bottle_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::bottle_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "781d2aa33ab4e61c17d06f9478782f3d";
  }

  static const char* value(const ::vision::bottle_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x781d2aa33ab4e61cULL;
  static const uint64_t static_value2 = 0x17d06f9478782f3dULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::bottle_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/bottle_data";
  }

  static const char* value(const ::vision::bottle_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::bottle_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped P\n\
float64 height\n\
float64 width\n\
int32 type\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::vision::bottle_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::bottle_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.P);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bottle_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::bottle_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::bottle_data_<ContainerAllocator>& v)
  {
    s << indent << "P: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.P);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_BOTTLE_DATA_H
